// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: groups.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
  group_name
) VALUES (
    $1
)RETURNING id, group_name
`

func (q *Queries) CreateGroup(ctx context.Context, groupName string) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, groupName)
	var i Group
	err := row.Scan(&i.ID, &i.GroupName)
	return i, err
}
