// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Todo struct {
	ID        int64     `json:"id"`
	TodoName  string    `json:"todo_name"`
	GroupName string    `json:"group_name"`
	CreatedAt time.Time `json:"created_at"`
	// oneof(ongoing, suspended, completed)
	Status   string    `json:"status"`
	Deadline time.Time `json:"deadline"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type UsersTodo struct {
	ID             int64 `json:"id"`
	UserID         int64 `json:"user_id"`
	TodosID        int64 `json:"todos_id"`
	HasPermissions bool  `json:"has_permissions"`
}
