// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	Creategroup(ctx context.Context, arg CreategroupParams) (Group, error)
	GetUser(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
