// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: todos.sql

package db

import (
	"context"
	"time"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
  group_id,
  todo_name,
  deadline
) VALUES (
    $1, $2, $3
) RETURNING id, group_id, todo_name, created_at, status, deadline
`

type CreateTodoParams struct {
	GroupID  int64     `json:"group_id"`
	TodoName string    `json:"todo_name"`
	Deadline time.Time `json:"deadline"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.GroupID, arg.TodoName, arg.Deadline)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TodoName,
		&i.CreatedAt,
		&i.Status,
		&i.Deadline,
	)
	return i, err
}
