// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: todos.sql

package db

import (
	"context"
	"time"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
  group_id,
  todo_name,
  deadline
) VALUES (
    $1, $2, $3
) RETURNING id, group_id, todo_name, created_at, status, deadline
`

type CreateTodoParams struct {
	GroupID  int64     `json:"group_id"`
	TodoName string    `json:"todo_name"`
	Deadline time.Time `json:"deadline"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.GroupID, arg.TodoName, arg.Deadline)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TodoName,
		&i.CreatedAt,
		&i.Status,
		&i.Deadline,
	)
	return i, err
}

const getTodosByGroupID = `-- name: GetTodosByGroupID :many
SELECT id, group_id, todo_name, created_at, status, deadline FROM todos WHERE todos.group_id IN (SELECT users_groups.group_id FROM users_groups WHERE user_id = $1 and users_groups.group_id = $2)
`

type GetTodosByGroupIDParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) GetTodosByGroupID(ctx context.Context, arg GetTodosByGroupIDParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByGroupID, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.TodoName,
			&i.CreatedAt,
			&i.Status,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByUserID = `-- name: GetTodosByUserID :many
SELECT id, group_id, todo_name, created_at, status, deadline FROM todos WHERE group_id IN (SELECT group_id FROM users_groups WHERE user_id = $1)
`

func (q *Queries) GetTodosByUserID(ctx context.Context, userID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.TodoName,
			&i.CreatedAt,
			&i.Status,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
