// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: users_groups.sql

package db

import (
	"context"
)

const assignUserToGroup = `-- name: AssignUserToGroup :one
INSERT INTO users_groups (
  user_id,
  group_id
) VALUES (
    $1, $2
)RETURNING id, user_id, group_id
`

type AssignUserToGroupParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) AssignUserToGroup(ctx context.Context, arg AssignUserToGroupParams) (UsersGroup, error) {
	row := q.db.QueryRowContext(ctx, assignUserToGroup, arg.UserID, arg.GroupID)
	var i UsersGroup
	err := row.Scan(&i.ID, &i.UserID, &i.GroupID)
	return i, err
}
