// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: users_todos.sql

package db

import (
	"context"
)

const createUsersTodos = `-- name: CreateUsersTodos :one
INSERT INTO users_todos (
  user_id,
  todos_id,
  has_permissions
) VALUES (
    $1, $2, $3
)RETURNING id, user_id, todos_id, has_permissions
`

type CreateUsersTodosParams struct {
	UserID         int64 `json:"user_id"`
	TodosID        int64 `json:"todos_id"`
	HasPermissions bool  `json:"has_permissions"`
}

func (q *Queries) CreateUsersTodos(ctx context.Context, arg CreateUsersTodosParams) (UsersTodo, error) {
	row := q.db.QueryRowContext(ctx, createUsersTodos, arg.UserID, arg.TodosID, arg.HasPermissions)
	var i UsersTodo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TodosID,
		&i.HasPermissions,
	)
	return i, err
}
